php-fpm:
  build: .
  dockerfile: ./Dockerfile
  container_name: laragym_php
  volumes:
    - .:/var/www/laravel
    - ~/.env:/var/www/laravel/.env
  links:
    - redis
  working_dir: /var/www/laravel
nginx:
  image: nginx:alpine
  container_name: laragym_nginx
  volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf
  links:
    - php-fpm
  ports:
    - 80:80
redis:
  image: redis:4.0.4-alpine
  container_name: laragym_redis
  volumes:
    - ~/redis_data:/data
