nginx:
  image: nginx:alpine
  container_name: laragym_nginx
  volumes_from:
    - php
  volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf
  links:
    - php
  ports:
    - 80:80
php:
  build: .
  dockerfile: ./Dockerfile
  container_name: laragym_php
  volumes:
    - .:/var/www/laravel
  links:
    - redis
redis:
  image: redis:alphine
  container_name: laragym_redis
  volumes:
    - ./resources/redis:/data
